apiVersion: v1
kind: Namespace
metadata:
  name: wanyang3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap-1
  namespace: wanyang3
data:
  DEPLOYMENT_ENV: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hwy-1
  namespace: wanyang3
  labels:
    app: demo-hwy-1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-hwy-1
  template:
    metadata:
      labels:
        app: demo-hwy-1
    spec:
      containers:
      - name: demo
        image: huwanyang168/demo:0.0.1
        imagePullPolicy: IfNotPresent
        args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOYMENT_ENV_KEY
          valueFrom:
            configMapKeyRef:
              name: demo-configmap-1
              key: DEPLOYMENT_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: demo-hwy-1
  namespace: wanyang3
  labels:
    app: demo-hwy-1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32124
  selector:
    app: demo-hwy-1